### ISSUE TITLE
Report to-do

### ISSUE THREAD

**Issue by louislefevre** [louislefevre/onyx#65]
- [x] Add links to user guide (wiki)
- [x] Edit implementation section
- [x] Add missing references
- [x] Add images
- [x] Add appendices
- [x] Add missing glossary terms
- [x] Peer review grammar
- [x] Refer to figures in text
